import { Gabarito } from "next/font/google";
import "./globals.css";

const gabarito = Gabarito({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props) {
  return (
    <html lang="en">
      <body className={gabarito.className}>
        <main>
          {props.children}
          {props.modal}
        </main>
      </body>
    </html>
  );
}
