import { Gabarito } from "next/font/google";
import "./globals.css";

const gabarito = Gabarito({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props) {
  console.log(props);
  return (
    <html lang="ru">
      <body className={gabarito.className}>
        {props.children}
        {props.modal}
      </body>
    </html>
  );
}
